//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseProgram.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        public int custID { get; set; }
        public string custName { get; set; }
        public int custAge { get; set; }
        public int custWeight { get; set; }
    }
}
