//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseProgram.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXERCISEMAX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXERCISEMAX()
        {
            this.EXERCISES = new HashSet<EXERCISES>();
        }
    
        public int exerciseMax1 { get; set; }
        public int exerciseID { get; set; }
    
        public virtual EXERCISES EXERCIS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXERCISES> EXERCISES { get; set; }
    }
}
