//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExerciseProgram.WebUI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXERCISES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXERCISES()
        {
            this.CATEGORies = new HashSet<CATEGORY>();
            this.EXERCISEMAXes = new HashSet<EXERCISEMAX>();
        }
    
        public int exerciseID { get; set; }
        public string exerciseName { get; set; }
        public byte[] exercisePic { get; set; }
        public string exerciseDesc { get; set; }
        public int exerciseMax { get; set; }
        public int catID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORY> CATEGORies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EXERCISEMAX> EXERCISEMAXes { get; set; }
        public virtual EXERCISEMAX EXERCISEMAX1 { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
    }
}
